builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - 386
    - amd64
  main: ./cmd/devcontainer/
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
